dist: bionic

os: linux

services:
  - docker
  - mysql

language: python

python:
  - 3.8

_iRODS_4_2_8: &iRODS_4_2_8
  env: DOCKER_IMAGE=wsinpg/ub-18.04-irods-4.2.8:latest IRODS_VERSION="==4.2.8" BATON_VERSION=">2.0.1"

env:
  global:
    - WSI_CONDA_CHANNEL=https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic/

jobs:
  include:
    - env: DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2.7:latest IRODS_VERSION="==4.2.7" BATON_VERSION=">2.0.1"
    - <<: *iRODS_4_2_8

  allow_failures:
    - <<: *iRODS_4_2_8

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a

install:
  - .travis/install.sh
  
script:
  - . ~/miniconda/etc/profile.d/conda.sh
  - conda activate travis
  - ienv
  - echo "irods" | script -q -c "iinit" /dev/null
  - ils
  - pytest --it
