sudo: false

services:
  - docker

language: python
python:
  - 3.7

env:
  global:
    - BATON_VERSION=2.0.1

  matrix:
    - DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest
    - DOCKER_IMAGE=wsinpg/ub-12.04-irods-4.1:latest

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a

install:
  - .travis/install.sh
  - pip install -r test-requirements.txt
  
script:
  - . ~/miniconda/etc/profile.d/conda.sh
  - conda activate travis
  - ienv
  - echo "irods" | script -q -c "iinit" /dev/null
  - ils
  - pytest --it
